dist: xenial
language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - for i in examples/*; do cargo run --example $(basename $i .rs) || true; done
