name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo test --verbose
    - run: cargo test --examples --verbose
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo clippy
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo fmt -- --check
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo doc
